# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: James McGuigan
email: james.mcguigan.personal@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Sometimes I like to try out new things, here are some of my experiments
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://jamesmcguigan.com" # the base hostname & protocol for your site
twitter_username:
github_username:  JamesMcGuigan
linkedin_username:  JamesMcGuigan

# Build settings
markdown: kramdown
